### ISSUE TITLE
can't use grid_load in matlab

### ISSUE THREAD

**Issue by GC0225** [MITgcm/gcmfaces#18]
I have put the nctiles_grid and gcmfaces in a same directory according to the v4r4 user guider. But when I  run the code with ECCOv4r4 like this:
p = genpath('gcmfaces/'); addpath(p);
p = genpath('MITprof/'); addpath(p);
grid_load
it will show that 'Unable to open file nctiles_grid\GRID.0001.nc'. 
The code is OK when I use ECCO v4r3. So how can I solve it?  Thank you.

**Comment by owang01** [comment]
@Bitterground The grids used for producing V4r4 and V4r3 are actual identical. So one way to get around it is just use V4r3's nctiles_grid when analyzing V4r4 using gcmfaces. The error is caused by different filenames that were used for V4r3 and V4r4 when converting the grid information to netCDF files. The two versions of netCDF files have different variables, which would also cause errors when using grid_load to read V4r4's nctile_grid files.

**Comment by Bitterground** [comment]
@owang01  Thank you for answer.  When I evaluate volume budget with V4r4, I come across with two other questions. 
(i). when I run the code like this: 
dir1 =  '/ECCOv4r4/nctiles_monthly/' ;
oceFWflx = read_nctiles( [dir1,'oceFWflx'],'oceFWflx',ii ) ;
It will show that ' error using of read_nctiles. /ECCOv4r4/nctiles_monthly/oceFWflx/oceFWflx*.nc not found'. 
I have downloaded and stored them in the subdirectory nctiles_monthly according to the example matlab code in ‘A Note on Practical Evaluation of Budgets in ECCO Version 4 Release 3'. 
(ii). I noticed your commit about update nctiles_read. But I have no idea how to add these changes in my computer. Do I need to make the same change line by line on the original code or is there another way?
Look forward to your reply.
